# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger: none
resources:
  containers:
  - container: myACRContainer  
    type: ACR
    azureSubscription: arm-rmdev-anumitareg
    resourceGroup: anumitaReg
    registry: ajAcr1
    repository: test
    trigger: 
      tags:
      - alpha*

pool:
  vmImageName: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script2'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'